{
 "title": "recomedations_Service",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "RAM utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"fastapi_app:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM utilisation by the time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"fastapi_app:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_count{instance=\"fastapi_app:8081\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of quries for 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{instance=\"fastapi_app:8081\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}