FROM python:3.11-slim

WORKDIR /app

# Ставим системные зависимости для numpy/scipy
RUN apt-get update && apt-get install -y --no-install-recommends \ 
    build-essential gcc g++ libopenblas-dev     && rm -rf /var/lib/apt/lists/*

# Только зависимости сервиса
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходники и модели
COPY app.py ./app.py
COPY src ./src
COPY models ./models
COPY config ./config

ENV PYTHONPATH=/app
ENV MODEL_DIR=/app/models

CMD uvicorn app:app --reload --host 0.0.0.0 --port ${APP_VM_PORT} 